const v = await (await fetch('http://127.0.0.1:9250/json/version')).json()
const ws = new WebSocket(v.webSocketDebuggerUrl)
await new Promise((ok, err) => { ws.onopen = ok; ws.onerror = err })
ws.send(JSON.stringify({ id: 1, method: 'Browser.close' }))
await new Promise(r => setTimeout(r, 1500))
process.exit(0)
