/**
 * 软件动作的中文名（纯数据模块，**不含任何 Node 内建依赖**）。
 *
 * 为什么要单独一份：渲染层（计划卡）需要动作名，但 `@shared/agent-tools` 会连带
 * `@shared/agent-domain-rules` → `node:crypto`，在浏览器构建里不可用（实测 build 直接失败）。
 *
 * 事实来源仍是 `agent-tools.ts` 的 AGENT_TOOL_CATALOG.label；
 * `tests/unit/agent-tools.test.ts` 有一条契约测试确保两份永远一致（漂移即测试失败）。
 */
export const AGENT_TOOL_LABELS: Record<string, string> = {
  listStores: '查看店铺列表',
  listTasks: '查看任务列表',
  listAgents: '查看主 Agent 状态',
  listJobs: '查看 Job 列表',
  commerceLedgerList: '查看电商动作台账',
  listTrashStores: '查看回收站',
  listBackups: '查看备份列表',
  getTaskDetail: '查看任务详情',
  createTask: '创建任务',
  searchMemory: '检索记忆',
  writeMemory: '写入记忆',
  openStore: '打开店铺',
  displayStore: '切换店铺',
  activateTab: '切换标签页',
  createTab: '新建标签页',
  navigateTab: '导航标签页',
  controlTab: '控制标签页导航',
  pinTab: '固定标签页',
  closeTab: '关闭标签页',
  closeStore: '关闭店铺',
  openPanel: '打开面板',
  createStore: '新建店铺',
  updateStore: '修改店铺',
  archiveStore: '移入回收站',
  restoreStore: '恢复店铺',
  deleteStorePermanent: '彻底删除店铺',
  deleteTask: '删除任务',
  runTask: '运行任务',
  pauseTaskRun: '暂停任务运行',
  resumeTaskRun: '恢复任务运行',
  cancelTaskRun: '取消任务运行',
  collectInvoices: '采集发票',
  collectBusiness: '采集经营数据',
  collectEntity: '采集主体信息',
  collectOrders: '采集订单明细',
  orderCollect: '采集统一订单',
  getOrderDetails: '查看订单明细',
  inventoryCollect: '采集库存价格',
  inventoryDiff: '比较库存价格',
  inventoryWriteback: '写回库存价格',
  skuCollect: '采集 SKU',
  skuDiff: '比较 SKU',
  skuWriteback: '写回 SKU',
  orderList: '查询订单',
  orderGet: '查看订单',
  fulfillmentPrepare: '准备发货',
  fulfillmentConfirm: '确认发货',
  fulfillmentVerify: '回读发货',
  afterSaleCollect: '采集售后',
  refundReview: '审核退款',
  refundConfirm: '确认退款',
  refundVerify: '回读退款',
  businessMetricsCollect: '采集经营指标',
  businessMetricsCompare: '比较经营指标',
  commerceHealth: '检查经营健康',
  invoiceCollect: '采集发票记录',
  invoiceExport: '导出发票',
  entityCollect: '采集经营主体',
  entityApply: '回填经营主体',
  contentDraft: '生成内容草稿',
  contentReview: '审核内容草稿',
  contentPublish: '发布内容',
  campaignPlan: '制定投放计划',
  couponPlan: '制定优惠券计划',
  adPlan: '制定广告计划',
  adConfirm: '确认广告投放',
  customerInbox: '查看客服收件箱',
  customerDraftReply: '生成客服草稿',
  customerSendReply: '发送客服回复',
  productSync: '同步商品',
  productList: '查看平台商品',
  productLibraryList: '查看本地商品库',
  productDetailCollect: '采集商品详情',
  productPublishPreflight: '预检商品发布',
  productPublishOpen: '打开商品发布页',
  productPublishVerify: '回读商品发布结果',
  productPublishReadback: '回读发布字段',
  productPublishAccept: '接受发布回读建议',
  productPublishChecklist: '查看发布补全清单',
  productPublishBatchProgress: '查看批量发布进度',
  listDownloads: '查看下载列表',
  listBookmarks: '查看书签',
  createBookmark: '新建书签',
  deleteBookmark: '删除书签',
  createBackup: '创建备份',
  restoreBackup: '恢复备份',
  listTools: '查看工具',
  listSkills: '查看技能',
  createSkill: '制作技能',
  runSkill: '运行技能',
  updateSkill: '更新技能',
  deleteSkill: '删除技能',
  createPlugin: '制作插件',
  listPlugins: '查看插件',
  runInvite: '发送达人邀约',
  getJobDetail: '查看 Job 详情',
  jobFeedback: '提交 Job 反馈',
  reviewJobResult: '审阅 Job 结果',
  approveJob: '批准或驳回 Job',
  resumeJob: '安全恢复 Job',
  cancelJob: '取消 Job',
  updatePlugin: '修改插件',
  deletePlugin: '删除插件',
  updateTask: '修改任务',
  overviewStats: '查看概览统计',
  overviewDatacenter: '查看数据中心',
  overviewInvoiceCenter: '查看发票中心',
  applyEntity: '回填店铺主体',
  qualityMetrics: '查看质量指标',
  qualityReview: '生成质量复盘',
  memoryRebuild: '重建记忆索引',
  memorySnapshot: '创建记忆快照',
}
