/**
 * 软件动作的中文名（纯数据模块，**不含任何 Node 内建依赖**）。
 *
 * 为什么要单独一份：渲染层（计划卡）需要动作名，但 `@shared/agent-tools` 会连带
 * `@shared/agent-domain-rules` → `node:crypto`，在浏览器构建里不可用（实测 build 直接失败）。
 *
 * 事实来源仍是 `agent-tools.ts` 的 AGENT_TOOL_CATALOG.label；
 * `tests/unit/agent-tools.test.ts` 有一条契约测试确保两份永远一致（漂移即测试失败）。
 */
export const AGENT_TOOL_LABELS: Record<string, string> = {
  listStores: '查看店铺列表',
  listTasks: '查看任务列表',
  listAgents: '查看子 Agent 列表',
  listJobs: '查看 Job 列表',
  listTrashStores: '查看回收站',
  listBackups: '查看备份列表',
  getTaskDetail: '查看任务详情',
  createTask: '创建任务',
  searchMemory: '检索记忆',
  writeMemory: '写入记忆',
  openStore: '打开店铺',
  displayStore: '切换店铺',
  activateTab: '切换标签页',
  createTab: '新建标签页',
  navigateTab: '导航标签页',
  controlTab: '控制标签页导航',
  pinTab: '固定标签页',
  closeTab: '关闭标签页',
  closeStore: '关闭店铺',
  openPanel: '打开面板',
  createAgent: '创建子 Agent',
  activateAgent: '激活子 Agent',
  pauseAgent: '暂停子 Agent',
  resumeAgent: '恢复子 Agent',
  retireAgent: '退休子 Agent',
  createStore: '新建店铺',
  updateStore: '修改店铺',
  archiveStore: '移入回收站',
  restoreStore: '恢复店铺',
  deleteStorePermanent: '彻底删除店铺',
  deleteTask: '删除任务',
  runTask: '派单运行任务',
  pauseTaskRun: '暂停任务运行',
  resumeTaskRun: '恢复任务运行',
  cancelTaskRun: '取消任务运行',
  collectInvoices: '采集发票',
  collectBusiness: '采集经营数据',
  collectEntity: '采集主体信息',
  collectOrders: '采集订单明细',
  getOrderDetails: '查看订单明细',
  listDownloads: '查看下载列表',
  listBookmarks: '查看书签',
  createBookmark: '新建书签',
  deleteBookmark: '删除书签',
  createBackup: '创建备份',
  restoreBackup: '恢复备份',
  listTools: '查看工具',
  listSkills: '查看技能',
  createSkill: '制作技能',
  runSkill: '运行技能',
  updateSkill: '更新技能',
  deleteSkill: '删除技能',
  createPlugin: '制作插件',
  listPlugins: '查看插件',
  runInvite: '发送达人邀约',
  getJobDetail: '查看 Job 详情',
  jobFeedback: '提交 Job 反馈',
  reviewJobResult: '审阅 Job 结果',
  approveJob: '批准或驳回 Job',
  resumeJob: '安全恢复 Job',
  cancelJob: '取消 Job',
  updateAgent: '修改子 Agent',
  bindAgentModel: '绑定模型 Profile',
  updatePlugin: '修改插件',
  deletePlugin: '删除插件',
  updateTask: '修改任务',
  overviewStats: '查看概览统计',
  overviewDatacenter: '查看数据中心',
  overviewInvoiceCenter: '查看发票中心',
  applyEntity: '回填店铺主体',
  qualityMetrics: '查看质量指标',
  qualityReview: '生成质量复盘',
  memoryRebuild: '重建记忆索引',
  memorySnapshot: '创建记忆快照',
}
