import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const studio = readFileSync('apps/desktop/src/renderer/src/features/workbench/UnifiedImageStudioPage.vue', 'utf8')
const dashboard = readFileSync('apps/desktop/src/renderer/src/features/workbench/DashboardView.vue', 'utf8')
const imageClient = readFileSync('apps/desktop/src/main/services/ai-client.ts', 'utf8')
const imageHandlers = readFileSync('apps/desktop/src/main/ipc/ai-handlers.ts', 'utf8')

describe('AI 商品图工作台页签细节', () => {
  it('保留参考站的模特、场景和自由编辑入口', () => {
    expect(studio).toContain('模特库')
    expect(studio).toContain('我的模特库')
    expect(studio).toContain('场景库')
    expect(studio).toContain('我的场景库')
    expect(studio).toContain('图片翻译')
    expect(studio).toContain('智能扩图')
    expect(studio).toContain('高清修复')
    expect(studio).toContain('背景替换')
    expect(studio).toContain('商品改色')
    expect(studio).toContain('杂物消除')
    expect(studio).toContain('edit-workspace')
    expect(studio).toContain('replicate-workspace')
    expect(studio).toContain('special-workspace')
    expect(studio).toContain('model-library-grid')
    expect(studio).toContain('智能推荐')
    expect(studio).toContain('material-examples-toggle')
    expect(studio).toContain('reference-site/product.jpg')
    expect(studio).toContain('image-studio-ratios')
    expect(studio).toContain('IMAGE_STUDIO_RATIO_OPTIONS')
    expect(studio).toContain('上传参考图抠图')
    expect(studio).toContain('requestSceneGeneration')
    expect(studio).toContain("const sceneSource = ref<'library' | 'ai' | 'mine'>('library')")
    expect(studio).toContain("const modelScene = ref('智能推荐')")
    expect(studio).toContain('说点什么...')
  })

  it('删除计费内容并保留参考站 AI 商品创作的风格与平台控件', () => {
    expect(studio).not.toContain('AI豆')
    expect(studio).not.toContain('充值')
    expect(studio).not.toContain('工单')
    expect(studio).not.toContain('手机预览')
    expect(studio).not.toContain('product-price')
    expect(studio).not.toContain('product-original-price')
    expect(studio).not.toContain('AI 整理卖点')
    expect(studio).not.toContain('在助手中查看')
    expect(studio).toContain("const detailCount = ref(2)")
    expect(studio).toContain('generationStyleOptions')
    expect(studio).toContain('platformOptions')
    expect(studio).toContain('generation-style-card')
    expect(studio).toContain('generation-platform-card')
    expect(studio).toContain("const generationStyle = ref('爆款风格')")
    expect(studio).toContain("const unifiedStyle = ref(false)")
    expect(studio).toContain("const platform = ref('通用')")
    expect(studio).toContain('生成风格：${generationStyle.value}')
    expect(studio).toContain('平台：${platform.value}')
    expect(studio).not.toContain('product-category-field')
    expect(studio).not.toContain('recognize-category')
  })

  it('限制与参考站一致并把复刻参考图完整传到主进程', () => {
    expect(studio).toContain("mode.value === 'model' ? 2")
    expect(studio).toContain('9 - competitorReferences.value.length')
    expect(studio).toContain("mode.value === 'edit' ? 2000")
    expect(studio).toContain('[...competitorReferences.value, ...materials.value]')
    expect(imageHandlers).toContain('input.sourceImages.slice(0, 10)')
    expect(imageClient).toContain('opts.sourceImages.slice(0, 10)')
    expect(studio).toContain('const sourceAssets = requestMode === \'edit\'')
    expect(studio).toContain('.map(toImageSource)')
  })

  it('复刻、模特、数量图共用固定底部操作栏，详情与编辑上传图标保持轻量线性样式', () => {
    expect(studio.match(/class="special-generate-footer"/g)).toHaveLength(3)
    expect(studio).toContain('data-test="replicate-generate-button"')
    expect(studio).toContain('data-test="model-generate-button"')
    expect(studio).toContain('data-test="quantity-generate-button"')
    expect(studio).toContain('.special-generate-footer{position:absolute;left:0;bottom:0')
    expect(studio).toContain('class="detail-upload-icon" viewBox="0 0 24 24"')
    expect(studio).toContain('.detail-upload-icon{display:block;width:22px;height:22px;fill:none;stroke:currentColor')
    expect(studio).toContain('.inline-tool-icon{width:13px;height:13px;fill:none;stroke:currentColor')
  })

  it('图片工作台仍保留主工作台左侧导航', () => {
    expect(dashboard).toContain("'picker-mode': taskPicking && activePage === 'browser'")
    expect(dashboard).toContain("'image-studio-shell': activePage === 'image-studio'")
    expect(dashboard).toContain('<aside class="dashboard-sidebar sidebar"')
    expect(dashboard).toContain('.image-studio-shell .dashboard-toolbar { display: none; }')
    expect(dashboard).not.toContain('.image-studio-shell .dashboard-sidebar')
    expect(dashboard).not.toContain('.image-studio-replica .dashboard-sidebar')
  })

  it('上传限制、输入长度与历史会话按参考站口径工作', () => {
    expect(studio).not.toContain('image/webp')
    expect(studio).toContain('accept=".jpg,.jpeg,.png,image/jpeg,image/png"')
    expect(studio).toContain('maxlength="200"')
    expect(studio).toContain('const editSessionRecords = computed')
    expect(studio).toContain('function optimizeEditPrompt()')
    expect(studio).not.toContain('@click="prompt = prompt.trim()"')
    expect(studio).toContain("const modelSource = ref<'library' | 'ai' | 'mine'>('library')")
    expect(studio).toContain("const detailRatio = ref('3:4')")
    expect(studio).toContain('aspectRatio: detailPreviewAspectRatio')
    expect(studio).not.toContain('font-auto-badge')
    expect(studio).toContain('const fontLicenseHint = \'可能存在版权风险，需要人工审核\'')
    expect(studio).toContain('if (mode.value === \'detail\') selectedRatio.value = next')
    expect(studio).toContain('aria-label="图片编辑要求"')
  })

  it('模特图的必选来源不会在未选择系统模特时漏发参考图', () => {
    expect(studio).toContain("modelSource.value === 'library' && !selectedSystemModelAsset.value")
    expect(studio).toContain('const modeNeedsLibraryAsset = computed(() => Boolean(libraryAssetRequirement.value))')
    expect(studio).toContain('modeNeedsLibraryAsset" @click="requestGeneration"')
    expect(studio).toContain('请先从模特库选择一个模特形象')
  })

  it('我的模特库和场景库必须显式选中，不会静默使用第一张上传图片', () => {
    expect(studio).toContain('modelLibraryUploads.value.find(item => item.name === modelAppearance.value) || null')
    expect(studio).toContain('sceneLibraryUploads.value.find(item => item.name === modelScene.value) || null')
    expect(studio).toContain('if (!modelLibraryUploads.value.some(item => item.name === modelAppearance.value)) modelAppearance.value = asset.name')
    expect(studio).toContain('if (!sceneLibraryUploads.value.some(item => item.name === modelScene.value)) modelScene.value = asset.name')
  })

  it('异步生成固定请求快照并拒绝丢失的素材，避免切换页签造成请求串线', () => {
    expect(studio).toContain('const requestMode = mode.value')
    expect(studio).toContain('const requestProductName = productName.value.trim()')
    expect(studio).toContain('let sourceImages: Array<{ name: string; mimeType: string; b64Json: string }> = []')
    expect(studio).toContain("generationError.value = '部分素材读取失败，请重新上传后再试。'")
    expect(studio).toContain('if (sourceImages.length !== sourceAssets.length)')
    expect(studio).toContain('部分素材读取失败，请重新上传后再试。')
    expect(studio).toContain('modeKey === \'replicate\' && competitorReferences.value.length')
    expect(studio).toContain('modeKey === \'edit\' && referenceMaterial.value')
  })

  it('竞品图和场景参考图都会验证真实图片内容，而不是只检查 MIME', () => {
    expect(studio).toContain('readImage(file, asset => { sceneReference.value = asset }')
    expect(studio).toContain('readImage(file, asset => { if (competitorReferences.value.length < 9) competitorReferences.value.push(asset) }')
  })

  it('生成中阻止离开图片工作台，并逐批持久化真实返回结果', () => {
    expect(studio).toContain("(event: 'busy-change', busy: boolean)")
    expect(studio).toContain("watch(generationBusy, busy => emit('busy-change', busy), { immediate: true })")
    expect(studio).toContain('historyImages.value = [...batch, ...historyImages.value].slice(0, 500)')
    expect(studio).toContain('persistHistory()')
    expect(dashboard).toContain('@busy-change="imageStudioBusy = $event"')
    expect(dashboard).toContain('function preventBusyImageStudioExit()')
    expect(dashboard).toContain("activePage.value !== 'image-studio' || !imageStudioBusy.value")
    expect(dashboard).toContain('if (page !== \'image-studio\' && preventBusyImageStudioExit()) return')
    expect(dashboard).toContain('if (preventBusyImageStudioExit()) return')
    expect(dashboard).toContain('if (preventBusyImageStudioExit()) {\n      // 主进程的原生店铺视图覆盖在渲染层上')
  })

  it('不保留已删除的重复导航和遗留计费样式', () => {
    expect(studio).not.toContain('class="head-actions"')
    expect(studio).not.toContain('.studio-nav')
    expect(studio).not.toContain('.studio-mode-hint')
    expect(studio).not.toContain('.detail-mode-nav')
    expect(studio).not.toContain('.detail-image-copy')
  })
})
